const surveySections = [
  { id: "consent", title: "Consent Statement", kicker: "Before you begin", type: "consent" },
  { id: "profile", title: "Part I. Respondent Profile", kicker: "Section 01", type: "profile" },
  { id: "instructions", title: "Instructions", kicker: "How to respond", type: "instructions" },
  { id: "functional-suitability", code: "A", title: "A. Functional Suitability", kicker: "Section 02", questions: ["The camera can detect birds as expected.", "The system can identify the birds correctly.", "The scarecrow responds when a bird is detected.", "The sound used to scare birds works properly.", "The app shows the bird detection information I need.", "The system saves the bird type, date, and time of each detection.", "I can see the saved bird detection records in the app.", "The system helps me check bird activity in the farm.", "The system is useful for helping protect rice crops from birds."] },
  { id: "performance-efficiency", code: "B", title: "B. Performance Efficiency", kicker: "Section 03", questions: ["The system detects birds quickly.", "The app opens and responds quickly.", "The system works smoothly during use.", "The Raspberry Pi and camera work together with minimal delay.", "The system can still work when there is no internet.", "The system uses power efficiently."] },
  { id: "usability", code: "C", title: "C. Usability", kicker: "Section 04", questions: ["The AgriGuard IoT system is easy to learn.", "The app is easy to navigate and use.", "The app is clear and easy to understand.", "The buttons and icons are easy to understand.", "I can easily find the features I need.", "The information shown in the app is easy to understand.", "I can use the system without special technical skills."] },
  { id: "reliability", code: "D", title: "D. Reliability", kicker: "Section 05", questions: ["The system works properly during use.", "The system rarely stops, freezes, or closes by itself.", "The bird detection feature works properly during use.", "Saved bird records are still available when I need them.", "The app shows my saved records correctly when I open it again.", "The system still works properly without internet."] },
  { id: "security", code: "E", title: "E. Security", kicker: "Section 06", questions: ["The system keeps bird records on the local network.", "The system works without internet.", "The app does not publicly share bird records.", "Bird records are stored only in the system.", "The app allows users to manually delete incorrect detection records, such as false detections of people."] },
  { id: "portability", code: "F", title: "F. Portability", kicker: "Section 07", questions: ["The app works properly on my phone.", "The app is easy to install.", "I can use the app without help from someone else.", "The app works properly on different Android phones.", "The system can be used properly in the farm."] },
  { id: "overall-assessment", code: "O", title: "Part III. Overall Assessment", kicker: "Section 08", questions: ["Overall, I am satisfied with AgriGuard IoT.", "I would recommend AgriGuard IoT to other rice farmers.", "AgriGuard IoT can help reduce damage caused by birds.", "AgriGuard IoT can help save time when checking for birds.", "AgriGuard IoT is useful compared with checking for birds by hand."] },
  { id: "open-ended", title: "Part IV. Open-Ended Questions", kicker: "Section 09", type: "open", questions: ["What feature did you like most? Why?", "Did you have any problems while using the system?", "What can we improve in the system?"] }
];

const ratingOptions = [{ value: "1", label: "1" }, { value: "2", label: "2" }, { value: "3", label: "3" }, { value: "4", label: "4" }, { value: "5", label: "5" }, { value: "NA", label: "N/A" }];
const scale = [["5", "Strongly Agree"], ["4", "Agree"], ["3", "Neutral"], ["2", "Disagree"], ["1", "Strongly Disagree"], ["N/A", "Not Applicable / Feature Not Used"]];
const form = document.querySelector("#survey-form");
const stepsContainer = document.querySelector("#survey-steps");
const status = document.querySelector("#form-status");
const previousButton = document.querySelector("#previous-button");
const nextButton = document.querySelector("#next-button");
let currentStep = 0;

function renderStepHeader(section) { return `<div class="step-header"><p class="step-kicker">${section.kicker}</p><h2>${section.title}</h2>${section.id === "instructions" ? "<p class=\"step-description\">Please select the response that best reflects your experience with the system.</p>" : ""}</div>`; }
function renderProfile() { return `<div class="profile-grid"><div class="field"><label for="age">Age <span class="required">*</span></label><input id="age" name="age" type="text" required></div><fieldset class="field radio-list"><legend>Sex: <span class="required">*</span></legend>${["Male", "Female", "Prefer not to say"].map(value => `<label><input type="radio" name="sex" value="${value}" required> ${value}</label>`).join("")}</fieldset><fieldset class="field radio-list"><legend>Occupation: <span class="required">*</span></legend>${["Rice Farmer", "Farm Owner", "Agricultural Worker", "Other"].map(value => `<label><input type="radio" name="occupation" value="${value}" required> ${value}</label>`).join("")}</fieldset><div class="field"><label for="education">Highest Education <span class="required">*</span></label><select id="education" name="highest_education" required><option value="">Select one</option>${["No Formal Education", "Elementary", "High School", "Vocational/Technical", "College"].map(value => `<option>${value}</option>`).join("")}</select></div><div class="field"><label for="farming">Years of Farming <span class="required">*</span></label><select id="farming" name="years_of_farming" required><option value="">Select one</option>${["Less than 5 years", "5–10 years", "11–20 years", "21 years and above"].map(value => `<option>${value}</option>`).join("")}</select></div><div class="field"><label for="smartphone">Smartphone Usage <span class="required">*</span></label><select id="smartphone" name="smartphone_usage" required><option value="">Select one</option>${["Daily", "Weekly", "Occasionally", "Rarely"].map(value => `<option>${value}</option>`).join("")}</select></div></div>`; }
function renderQuestion(section, text, index) { const id = `${section.id}-${index + 1}`; const code = `${section.code}${index + 1}`; return `<fieldset class="rating-card" data-question="${code}"><legend>${code}. ${text} <span class="required">*</span></legend><div class="rating-options">${ratingOptions.map(option => `<span class="rating-option"><input id="${id}-${option.value}" type="radio" name="${code}" value="${option.value}" required><label for="${id}-${option.value}">${option.label}</label></span>`).join("")}</div></fieldset>`; }
function renderOpen(section) { return `<div class="profile-grid">${section.questions.map((text, index) => `<div class="field full"><label for="open-${index + 1}">${index + 1}. ${text}</label><textarea id="open-${index + 1}" name="open_${index + 1}"></textarea></div>`).join("")}</div>`; }
function renderSteps() { stepsContainer.innerHTML = surveySections.map((section, index) => { let body = ""; if (section.type === "consent") body = `<div class="consent-copy"><p>Participation in this survey is voluntary. The information you provide will be used for the academic evaluation of the AgriGuard IoT: Solar-Powered Smart Scarecrow System. You may choose not to answer any question or withdraw at any time. Your responses will be kept confidential and used only for research purposes.</p></div><label class="checkbox-line"><input type="checkbox" name="consent" value="I agree to participate in this survey." required><span>I agree to participate in this survey. <span class="required">*</span></span></label>`; else if (section.type === "profile") body = renderProfile(); else if (section.type === "instructions") body = `<div class="scale-list">${scale.map(item => `<div class="scale-item"><span class="scale-score">${item[0]}</span><span>${item[1]}</span></div>`).join("")}</div>`; else if (section.type === "open") body = renderOpen(section); else body = `<div class="rating-list">${section.questions.map((text, questionIndex) => renderQuestion(section, text, questionIndex)).join("")}</div>`; return `<section class="step${index === 0 ? " active" : ""}" data-step="${index}" aria-hidden="${index !== 0}">${renderStepHeader(section)}${body}</section>`; }).join(""); }
function updateProgress() { const total = surveySections.length; const percent = Math.round(((currentStep + 1) / total) * 100); document.querySelector("#step-label").textContent = `Step ${currentStep + 1} of ${total}`; document.querySelector("#progress-percent").textContent = `${percent}%`; const bar = document.querySelector("#progress-bar"); bar.style.width = `${percent}%`; document.querySelector("[role=progressbar]").setAttribute("aria-valuenow", currentStep + 1); previousButton.disabled = currentStep === 0; nextButton.innerHTML = currentStep === total - 1 ? "Submit UAT Survey <span aria-hidden=\"true\">→</span>" : "Next <span aria-hidden=\"true\">→</span>"; }
function showStep(index) { document.querySelectorAll(".step").forEach((step, stepIndex) => { step.classList.toggle("active", stepIndex === index); step.setAttribute("aria-hidden", stepIndex !== index); }); currentStep = index; updateProgress(); status.textContent = ""; document.querySelector(".survey-card").scrollIntoView({ behavior: "smooth", block: "start" }); }
function validateCurrentStep() { const step = document.querySelector(`.step[data-step="${currentStep}"]`); step.querySelectorAll(".invalid").forEach(element => element.classList.remove("invalid")); const fields = [...step.querySelectorAll("input, select, textarea")]; const invalid = fields.find(field => !field.checkValidity()); if (!invalid) return true; const group = invalid.closest(".rating-card, .field, .checkbox-line"); if (group) group.classList.add("invalid"); invalid.focus(); status.textContent = "Please complete the required item before continuing."; return false; }
function calculateMean(values) { const valid = values.map(Number).filter(value => Number.isFinite(value) && value >= 1 && value <= 5); return valid.length ? valid.reduce((sum, value) => sum + value, 0) / valid.length : null; }
function interpretation(mean) { if (mean === null) return "No valid responses"; if (mean >= 4.21) return "Strongly Agree"; if (mean >= 3.41) return "Agree"; if (mean >= 2.61) return "Neutral"; if (mean >= 1.81) return "Disagree"; return "Strongly Disagree"; }
function calculateSurveyResults(data = new FormData(form)) { const questionMeans = {}; const categoryMeans = {}; const numericValues = []; surveySections.filter(section => section.questions && !section.type).forEach(section => { const values = []; section.questions.forEach((_, index) => { const code = `${section.code}${index + 1}`; const value = data.get(code); const mean = calculateMean([value]); questionMeans[code] = mean; if (mean !== null) { values.push(mean); numericValues.push(mean); } }); categoryMeans[section.title] = calculateMean(values); }); return { questionMeans, categoryMeans, overallMean: calculateMean(numericValues), interpretation }; }
renderSteps(); updateProgress();
nextButton.addEventListener("click", () => { if (!validateCurrentStep()) return; if (currentStep < surveySections.length - 1) showStep(currentStep + 1); else form.submit(); });
previousButton.addEventListener("click", () => { if (currentStep > 0) showStep(currentStep - 1); });
form.addEventListener("submit", event => { if (!validateCurrentStep()) event.preventDefault(); });
window.AgriGuardSurvey = { surveySections, calculateMean, interpretation, calculateSurveyResults };
